database.dsn=root:kd123456789@tcp(219.151.187.115:3306)/kenaito_vhost_gateway?charset=utf8mb4&parseTime=True&loc=Local
minio.endpoint=192.168.235.128:9000
minio.accessKey=root
minio.secretKey=kd123456789
minio.useSsl=false
minio.bucket=web-static
